// 追加事件：系统只接受"新事件"，任何修正都以新事件表达。
// 已入库事件不可修改——原始电子靶读数、裁判签名、现场显示全部保留。
//
// 事件分类：
//   赛事实体   COMPETITION_OPENED / ATHLETE_REGISTERED / TEAM_REGISTERED /
//              LANE_DEVICE_REGISTERED / ATHLETE_LANE_ASSIGNED
//   赛前检查   CALIBRATION_CHECK / TIME_SYNC_CHECK / START_CONFIRMED / EQUIPMENT_CHECK
//   原始流     SHOT_RECORDED（电子靶）/ SHOTS_SIGNED（裁判签名覆盖）
//   追加修正   SHOT_VOIDED / RESHOT_AWARDED / PENALTY_DEDUCTED / ATHLETE_WITHDRAWN
//   申诉       PROTEST_FILED / PROTEST_RESOLVED
//   认定链     DISPLAY_SNAPSHOT_FROZEN / GATE_EVIDENCE_SUBMITTED /
//              MEDIA_FLASH_PUBLISHED / VERSION_PUBLISHED / VERSION_CERTIFIED /
//              RECORD_RATIFIED

export const EVENT_TYPES = Object.freeze({
  COMPETITION_OPENED: "COMPETITION_OPENED",
  ATHLETE_REGISTERED: "ATHLETE_REGISTERED",
  TEAM_REGISTERED: "TEAM_REGISTERED",
  LANE_DEVICE_REGISTERED: "LANE_DEVICE_REGISTERED",
  ATHLETE_LANE_ASSIGNED: "ATHLETE_LANE_ASSIGNED",
  CALIBRATION_CHECK: "CALIBRATION_CHECK",
  TIME_SYNC_CHECK: "TIME_SYNC_CHECK",
  START_CONFIRMED: "START_CONFIRMED",
  EQUIPMENT_CHECK: "EQUIPMENT_CHECK",
  SHOT_RECORDED: "SHOT_RECORDED",
  SHOT_VOIDED: "SHOT_VOIDED",
  RESHOT_AWARDED: "RESHOT_AWARDED",
  PENALTY_DEDUCTED: "PENALTY_DEDUCTED",
  ATHLETE_WITHDRAWN: "ATHLETE_WITHDRAWN",
  SHOTS_SIGNED: "SHOTS_SIGNED",
  PROTEST_FILED: "PROTEST_FILED",
  PROTEST_RESOLVED: "PROTEST_RESOLVED",
  DISPLAY_SNAPSHOT_FROZEN: "DISPLAY_SNAPSHOT_FROZEN",
  GATE_EVIDENCE_SUBMITTED: "GATE_EVIDENCE_SUBMITTED",
  MEDIA_FLASH_PUBLISHED: "MEDIA_FLASH_PUBLISHED",
  VERSION_PUBLISHED: "VERSION_PUBLISHED",
  VERSION_CERTIFIED: "VERSION_CERTIFIED",
  RECORD_RATIFIED: "RECORD_RATIFIED",
});

// 弹着作废原因码（ISSf 裁判语境）
export const VOID_REASONS = Object.freeze({
  CALIBRATION_DRIFT: "CALIBRATION_DRIFT", // 靶位校准漂移
  EQUIPMENT_FAILURE: "EQUIPMENT_FAILURE", // 器材故障
  PROTEST_UPHELD: "PROTEST_UPHELD", // 申诉成立
  RULE_INFRINGEMENT: "RULE_INFRINGEMENT", // 违例弹
  SCORING_ERROR: "SCORING_ERROR", // 计分系统错误
});

export function createEvent(type, payload, meta = {}) {
  if (!type || !EVENT_TYPES[type]) throw new Error(`未知事件类型: ${String(type)}`);
  if (!meta.atUtc) throw new Error("事件必须带 atUtc 时刻");
  return {
    type,
    ...structuredClone(payload),
    atUtc: meta.atUtc,
    actorId: meta.actorId ?? null,
    actorRole: meta.actorRole ?? null,
    source: meta.source ?? "manual",
  };
}
